apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: compliment-generator
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: compliment-generator
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s